POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
  "name": "Jaakko Kaakko",
  "number": "123456789"
}

###

POST https://fullstack-open-part3-backend-9t1x.onrender.com/api/persons HTTP/1.1
Content-Type: application/json

{
  "name": "Jaakko Kaakko",
  "number": "123456789"
}